version: 0.0
os: linux
files:
    - source: /
      destination: /server
hooks:
    BeforeInstall:
        - location: scripts/preinstall.sh
          timeout: 300
          runas: root
    ApplicationStart:
        - location: scripts/startup.sh
          timeout: 300
          runas: root
    ApplicationStop:
        - location: scripts/shutdown.sh
          timeout: 300
          runas: root
    ValidateService:
        - location: scripts/validate.sh
          timeout: 300
          runas: root
