version: 0.2

phases:
    install:
        runtime-versions:
            golang: 1.12
    build:
        commands:
            - cd portal
            - GO111MODULE=on go build -o ../bin/portal
artifacts:
    files:
        - bin/portal
        - portal/template/**/*
        - appspec.yml
        - scripts/**/*
