version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
    build:
        commands:
            - npm install
            - npm run-script build
artifacts:
    files:
        - build/**/*
        - appspec.yml
        - scripts/**/*
